name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Maven Clean Install
        run: mvn clean install --file backend/pom.xml

      - name: Run Spring Boot Application
        run: mvn spring-boot:run --file backend/pom.xml

      - name: Serve Frontend
        run: |
          cd frontend
          npm install
          npx serve .
